// Generated by scripts/generate-acpx-sidecar-contract.mjs. Do not edit.

pub const GENERATED_ACPX_SIDECAR_PROTOCOL_VERSION: u64 = 2;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GeneratedAcpxSidecarCommand {
    Initialize,
    SessionOpen,
    RunAttach,
    TurnStart,
    TurnCancel,
    PermissionResolve,
    InputResolve,
    ToolResolve,
    SessionRead,
    SessionSnapshot,
    SessionSuspend,
    SessionClose,
}

impl GeneratedAcpxSidecarCommand {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Initialize => "initialize",
            Self::SessionOpen => "session.open",
            Self::RunAttach => "run.attach",
            Self::TurnStart => "turn.start",
            Self::TurnCancel => "turn.cancel",
            Self::PermissionResolve => "permission.resolve",
            Self::InputResolve => "input.resolve",
            Self::ToolResolve => "tool.resolve",
            Self::SessionRead => "session.read",
            Self::SessionSnapshot => "session.snapshot",
            Self::SessionSuspend => "session.suspend",
            Self::SessionClose => "session.close",
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Deserialize)]
pub enum GeneratedAcpxSidecarEventType {
    #[serde(rename = "runtime.event")]
    RuntimeEvent,
    #[serde(rename = "runtime.permission_requested")]
    RuntimePermissionRequested,
    #[serde(rename = "runtime.input_requested")]
    RuntimeInputRequested,
    #[serde(rename = "runtime.tool_called")]
    RuntimeToolCalled,
    #[serde(rename = "runtime.turn_terminal")]
    RuntimeTurnTerminal,
    #[serde(rename = "runtime.process")]
    RuntimeProcess,
    #[serde(rename = "runtime.diagnostic")]
    RuntimeDiagnostic,
}
