// Generated by scripts/generate-acpx-sidecar-contract.mjs. Do not edit.

export const GENERATED_ACPX_SIDECAR_PROTOCOL_VERSION = 2 as const;
export const GENERATED_ACPX_SIDECAR_COMMANDS = [
  "initialize",
  "session.open",
  "run.attach",
  "turn.start",
  "turn.cancel",
  "permission.resolve",
  "input.resolve",
  "tool.resolve",
  "session.read",
  "session.snapshot",
  "session.suspend",
  "session.close",
] as const;
export type GeneratedAcpxSidecarCommand =
  (typeof GENERATED_ACPX_SIDECAR_COMMANDS)[number];

export const GENERATED_ACPX_SIDECAR_EVENT_TYPES = [
  "runtime.event",
  "runtime.permission_requested",
  "runtime.input_requested",
  "runtime.tool_called",
  "runtime.turn_terminal",
  "runtime.process",
  "runtime.diagnostic",
] as const;
export type GeneratedAcpxSidecarEventType =
  (typeof GENERATED_ACPX_SIDECAR_EVENT_TYPES)[number];
